; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SBC client"
#define MyAppVersion "1.3.1"
#define MyAppPublisher "Ngor the Engineer"
#define MyAppExeName "SBC executable v3.exe"
#define MyAppAssocName MyAppName + " toolbox"
#define MyAppAssocExt ".sbc"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2132787E-70AF-4355-B3C8-B1A5D9F0DB97}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName=C:\SBC version 1.3.1\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Simple BlockChain setup 1.3.1
SolidCompression=yes
WizardStyle=modern dark windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\error.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\settings.stng"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\static_img.jpg"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\static2.jpg"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\vid.mp4"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\vid_res.mp4"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\pycharm_projects\BlockChain mk3\dist\SBC version 1.3\_internal\*"; DestDir: "{app}\_internal\"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runasoriginaluser